name: Vulncheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  govulncheck:
    name: Check for vulnerabilities
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod
          output-format: sarif
          output-file: govuln.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: govuln.sarif
          category: govulncheck
      - name: Check SARIF for error-level vulnerabilities
        run: |
          if jq '.runs[].results[] | select(.level == "error") | length > 0' govuln.sarif; then
            echo "Error-level vulnerabilities found in SARIF file"
            exit 1
          else
            echo "No error-level vulnerabilities found in SARIF file"
          fi